
// async/ await
const myFunc = () => {
	return new Promise((resolve, reject) => {
		 setTimeout (
			function() {
				throw new Error('Meu erro fabricado aqui!!!');
			},
			2000
		);
	});
};
await myFunc();


// promise
const myFunc = () => {
	return new Promise((resolve, reject) => {
		 setTimeout (
			function() {
				throw new Error('Meu erro fabricado aqui!!!');
			},
			2000
		);
	});
};
myFunc()
.then (
	() => {


... codigo


	}
)
.catch (
	err => {
		reject(err);
	}
);
