

// sync
throw new Error('Meu erro sync fabricado aqui!!!');


// async / await
const myFunc = () => {
	return new Promise((resolve, reject) => {
		 setTimeout (
			function() {
				reject (
					new Error('Meu erro async fabricado aqui!!!')
				)
			},
			2000
		);
	});
};
await myFunc();


// promise
const myFunc = () => {
	return new Promise((resolve, reject) => {
		 setTimeout (
			function() {
				reject (
					new Error('Meu erro async fabricado aqui!!!')
				)
			},
			2000
		);
	});
};
myFunc()
.catch (
	err => {
		reject(err);
	}
);
